### ISSUE TITLE
Publish 1.1.1 to npm

### ISSUE THREAD

**Issue by karolk** [tj/react-click-outside#26]
An older version of this project is published on npm here https://www.npmjs.com/package/react-click-outside-component by @aesopwolf but it uses deprecated version of PropTypes. This repo now has 1.1.1 in the package.json (but on in releases). Could we have the latest version of this on npm please?

**Comment by aesopwolf** [comment]
I'll publish the newest version to npm right now

**Comment by aesopwolf** [comment]
Published https://www.npmjs.com/package/react-click-outside-component

**Comment by karolk** [comment]
@aesopwolf looks good 👍
