### ISSUE TITLE
Doesn't work if you click outside, over an iFrame

### ISSUE THREAD

**Issue by umarashfaq** [tj/react-click-outside#29]
Use case:
- You have a menu A.
- You have a callback X, which is to be triggered if a click is detected outside A (using this library).
- Somewhere on the page, you have an iFrame B.
- When A is visible, and you click anywhere on the page, X gets invoked (working correct).
- When A is visible, and you click anywhere over B, X doesn't get invoked (bug).

version: 3.0.0

**Comment by royalparihar** [comment]
Hey @umarashfaq did you solve this issue
